### ISSUE TITLE
question about ‘Unknown v packet’

### ISSUE THREAD

**Issue by bobyan1979** [pulp-platform/debug_bridge#1]
After debug_bridge running in the zedboard's host(arm cortex-A9)，I try to connect the gdb server. This infomation shows:

> (gdb) target remote 192.168.1.7:1234
> Remote debugging using 192.168.1.7:1234
> Ignoring packet error, continuing...
> Remote replied unexpectedly to 'vMustReplyEmpty': timeout

and, the debug_bridge show the follwing error:

> RSP: Client connected!
> Received $qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+
> Sending $PacketSize=256#cd
> Received $vMustReplyEmpty
> Unknown v packet
> Debug bridge listening on port 1234

I don't know what happens, can you give some advices? Thanks.

**Comment by haugoug** [comment]
It looks like the gdb version you are using is not well aligned, where did you get it ?

**Comment by bobyan1979** [comment]
@haugoug 
I got it from https://github.com/riscv/riscv-gnu-toolchain, and surely it is a version problem.
Before the version of GDB 7.7, the gdb server should respone a 'OK' packet if receiving an unkown v packet. After modifying the file remote.c, debug server works.
So, close the issue and Thanks.

**Comment by GSpinach** [comment]
> @haugoug
> I got it from https://github.com/riscv/riscv-gnu-toolchain, and surely it is a version problem.
> Before the version of GDB 7.7, the gdb server should respone a 'OK' packet if receiving an unkown v packet. After modifying the file remote.c, debug server works.
> So, close the issue and Thanks.

 Hi, @bobyan1979 
Can you tell me how to modify the remote file ？
Thanks！
