### ISSUE TITLE
gdb debug through uart

### ISSUE THREAD

**Issue by machonghe** [pulp-platform/debug_bridge#11]
Hi, I have the PULPino project running on my fpga (zynq), and there is only one uart connection with my PC. How can I debug it with gdb? I have riscv32-gdb on PC, and I can connect to fpga board with minicom and run debug_brige on it. Maybe there is a way to modify the debug_bridge to make it work through uart, but I don't know how to. Look forward to your response!

Thanks.

**Comment by haugoug** [comment]
The debug unit is memory mapped so you need to do memory mapped accesses to control pulpino from gdb. This is usually done through jtag or spi. If you want to do it though uart, you would need to implement some HW in pulpino to translate the uart stream into memory-mapped requests. IThen modifying the bridge to support that should not be a big deal.

**Comment by machonghe** [comment]
Uh, I see. Thanks, for your time.
