### ISSUE TITLE
Remote replied unexpectedly to 'vMustReplyEmpty'

### ISSUE THREAD

**Issue by leverxin** [pulp-platform/debug_bridge#9]
Remote replied unexpectedly to 'vMustReplyEmpty'
===================================================================
GDB tools send vMustReplyEmpty packet to debug_bridge. But rsp.cpp decode part can not support this vMustReplyEmpty command. What should I do for this problem?
Should I need to change the version of riscv gdb?
thanks very much.

here is the debug_bridge log:
Found a core with id 7F02
Received $qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+
Sending $PacketSize=256#cd
Received $vMustReplyEmpty
Unknown v packet

Here is the gdb log:
/opt/riscv/bin$ riscv32-unknown-elf-gdb -ex "target remote 127.0.0.1:1234"
GNU gdb (GDB) 8.0.50.20170724-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-pc-linux-gnu --target=riscv32-unknown-elf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Remote debugging using 127.0.0.1:1234
Ignoring packet error, continuing...
Remote replied unexpectedly to 'vMustReplyEmpty': timeout
(gdb)

**Comment by haugoug** [comment]
This is due to the debug bridge not supporting recent gdb versions. You can have a look here for a work-around:
https://github.com/pulp-platform/debug_bridge/issues/1

**Comment by leverxin** [comment]
Thanks.  And do you know which riscv-gdb version the debug bridge can support.

**Comment by haugoug** [comment]
This is the commit I'm using but I cannot find it again on the web:
commit 2a3cd80468d00f13d4557401aa4c92100abf0cd3
Merge: ff4b34f 2461026
Author: Mike Frysinger <vapier@gmail.com>
Date:   Tue Mar 15 02:01:26 2016 -0400

    Merge pull request #4 from timsifive/riscv-rebase-2016.02.11
    
    sync riscv sim w/latest upstream sim changes

**Comment by FrancescoConti** [comment]
You can get it from here: https://github.com/riscv/riscv-binutils-gdb/tree/2a3cd80

**Comment by smitjshah** [comment]
I got the same issue while working on KGDB, So in my case i was using the servo board so in configuration the port which we were giving is wrong. We correct the port number and VOILA ! it works.

**Comment by kong-ling-hui** [comment]
I also ran into this problem. I tried the gdb from this repository, but it still threw errors. I found that I not only had the issue mentioned in this thread, but also encountered timeout errors. So I set "set remotetimeout 60" and that resolved the problem.
